# Generated by Django 5.2.7 on 2026-03-29 15:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_branch_options_alter_city_options'),
        ('permissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, help_text='If set, role applies only to this branch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to='core.branch')),
                ('city', models.ForeignKey(blank=True, help_text='If set, role applies only to this city', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to='core.city')),
                ('department', models.ForeignKey(blank=True, help_text='If set, role applies only to this department', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to='core.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roles_granted', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_revoked', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to='permissions.role')),
            ],
            options={
                'verbose_name': 'Employee Role',
                'verbose_name_plural': 'Employee Roles',
                'indexes': [models.Index(fields=['employee'], name='permissions_employe_628bdc_idx'), models.Index(fields=['role'], name='permissions_role_id_672106_idx'), models.Index(fields=['is_active'], name='permissions_is_acti_b7b9d7_idx'), models.Index(fields=['employee', 'is_active'], name='permissions_employe_223011_idx')],
                'unique_together': {('employee', 'role', 'city', 'branch', 'department')},
            },
        ),
    ]
