# Generated by Django 5.2.7 on 2026-03-29 15:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_branch_options_alter_city_options'),
        ('permissions', '0002_employeerole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeExtraPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, help_text='Why was this extra permission granted?')),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration for temporary permissions', null=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, help_text='If set, permission applies only to this branch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_extra_permissions', to='core.branch')),
                ('city', models.ForeignKey(blank=True, help_text='If set, permission applies only to this city', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_extra_permissions', to='core.city')),
                ('department', models.ForeignKey(blank=True, help_text='If set, permission applies only to this department', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_extra_permissions', to='core.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_permissions', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='extra_permissions_granted', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_extra_permissions', to='permissions.permission')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_permissions_revoked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Extra Permission',
                'verbose_name_plural': 'Employee Extra Permissions',
                'indexes': [models.Index(fields=['employee'], name='permissions_employe_a5e52b_idx'), models.Index(fields=['permission'], name='permissions_permiss_e1669d_idx'), models.Index(fields=['is_active'], name='permissions_is_acti_e7259b_idx'), models.Index(fields=['employee', 'is_active'], name='permissions_employe_d9ebc0_idx'), models.Index(fields=['expires_at'], name='permissions_expires_74577c_idx')],
                'unique_together': {('employee', 'permission', 'city', 'branch', 'department')},
            },
        ),
    ]
