# Generated by Django 5.2.7 on 2026-03-29 16:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_branch_options_alter_city_options'),
        ('permissions', '0003_employeeextrapermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegationRight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('can_delegate_permission', models.ForeignKey(help_text='Which permission can this employee delegate?', on_delete=django.db.models.deletion.CASCADE, related_name='delegation_rights', to='permissions.permission')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegation_rights', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegation_rights_granted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delegation Right',
                'verbose_name_plural': 'Delegation Rights',
                'indexes': [models.Index(fields=['employee'], name='permissions_employe_3c1a71_idx'), models.Index(fields=['can_delegate_permission'], name='permissions_can_del_e6c4a5_idx'), models.Index(fields=['is_active'], name='permissions_is_acti_42b9bf_idx')],
                'unique_together': {('employee', 'can_delegate_permission')},
            },
        ),
        migrations.CreateModel(
            name='PermissionDelegation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('delegated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration for temporary delegation', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, help_text='If set, delegation applies only to this branch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_delegations', to='core.branch')),
                ('city', models.ForeignKey(blank=True, help_text='If set, delegation applies only to this city', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_delegations', to='core.city')),
                ('delegate', models.ForeignKey(help_text='Employee receiving the permission', on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL)),
                ('delegator', models.ForeignKey(help_text='Employee giving the permission', on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='If set, delegation applies only to this department', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_delegations', to='core.department')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='permissions.permission')),
            ],
            options={
                'verbose_name': 'Permission Delegation',
                'verbose_name_plural': 'Permission Delegations',
                'indexes': [models.Index(fields=['delegator'], name='permissions_delegat_7b0b0c_idx'), models.Index(fields=['delegate'], name='permissions_delegat_8319ae_idx'), models.Index(fields=['permission'], name='permissions_permiss_ae0211_idx'), models.Index(fields=['is_active'], name='permissions_is_acti_6f5d65_idx'), models.Index(fields=['delegate', 'is_active'], name='permissions_delegat_ddac10_idx'), models.Index(fields=['expires_at'], name='permissions_expires_796ec9_idx')],
                'unique_together': {('delegator', 'delegate', 'permission')},
            },
        ),
    ]
