# Generated by Django 5.2.7 on 2026-04-05 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0004_delegationright_permissiondelegation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='delegationright',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='delegationright',
            name='can_delegate_permission',
        ),
        migrations.RemoveField(
            model_name='delegationright',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='delegationright',
            name='granted_by',
        ),
        migrations.AlterUniqueTogether(
            name='permissiondelegation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='permissiondelegation',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='permissiondelegation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='permissiondelegation',
            name='delegate',
        ),
        migrations.RemoveField(
            model_name='permissiondelegation',
            name='delegator',
        ),
        migrations.RemoveField(
            model_name='permissiondelegation',
            name='department',
        ),
        migrations.RemoveField(
            model_name='permissiondelegation',
            name='permission',
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='employeeextrapermission',
            name='permissions_expires_74577c_idx',
        ),
        migrations.RemoveIndex(
            model_name='role',
            name='permissions_hierarc_9b3c7c_idx',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='is_delegatable',
            new_name='can_be_given',
        ),
        migrations.AlterUniqueTogether(
            name='employeeextrapermission',
            unique_together={('employee', 'permission')},
        ),
        migrations.RemoveField(
            model_name='role',
            name='hierarchy_level',
        ),
        migrations.AlterField(
            model_name='employeeextrapermission',
            name='granted_by',
            field=models.ForeignKey(help_text='Employee who granted this permission (could be super admin or another employee with give_own permission)', on_delete=django.db.models.deletion.PROTECT, related_name='extra_permissions_granted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DelegationRight',
        ),
        migrations.DeleteModel(
            name='PermissionDelegation',
        ),
        migrations.RemoveField(
            model_name='employeeextrapermission',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='employeeextrapermission',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='employeeextrapermission',
            name='revoked_at',
        ),
        migrations.RemoveField(
            model_name='employeeextrapermission',
            name='revoked_by',
        ),
    ]
