# Generated by Django 5.2.7 on 2026-02-08 17:45

import cloudinary.models
import employees.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('rest_of_name', models.CharField(max_length=150)),
                ('date_joined', models.DateField(verbose_name='Date Joined')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('phone_number1', models.CharField(max_length=20, unique=True, validators=[employees.models.validate_egyptian_phone_number], verbose_name='Primary Phone Number')),
                ('phone_number2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Secondary Phone Number')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified')),
                ('identity_type', models.CharField(choices=[('nid', 'National ID'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('other', 'Other')], default='nid', max_length=20)),
                ('identity_number', models.CharField(max_length=20, unique=True, verbose_name='Government ID, Passport, etc...')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('location', models.URLField(blank=True, max_length=512, null=True)),
                ('role', models.CharField(default='employee', max_length=50)),
                ('profile_picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_pictures')),
                ('fingerprint_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
