# Generated by Django 5.2.7 on 2026-03-03 13:57

import django.db.models.deletion
import django.utils.timezone
import employees.models.employee
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Job title in Arabic', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job Title',
                'verbose_name_plural': 'Job Titles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number1', models.CharField(help_text='Egyptian phone with +20 prefix: +201xxxxxxxxx, used as unique identifier and for auth', max_length=13, unique=True, validators=[employees.models.employee.validate_egyptian_phone_number], verbose_name='Primary Phone Number')),
                ('phone_number2', models.CharField(blank=True, help_text='Optional alternative number', max_length=13, null=True, verbose_name='Secondary Phone Number')),
                ('fingerprint_id', models.CharField(blank=True, help_text='Format: FP{CityCode}{DeptCode}{Gender}{DeviceID}, e.g., FPCaITF138', max_length=20, null=True, unique=True)),
                ('national_id', models.CharField(blank=True, help_text='Egyptian National ID (14 digits)', max_length=14, null=True, unique=True, validators=[employees.models.employee.validate_egyptian_national_id])),
                ('first_name', models.CharField(help_text='First name in Arabic', max_length=50)),
                ('second_name', models.CharField(help_text='Father name in Arabic', max_length=50)),
                ('third_name', models.CharField(help_text='Grandfather name in Arabic', max_length=50)),
                ('fourth_name', models.CharField(help_text='Family name in Arabic', max_length=50)),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('address', models.TextField(blank=True, help_text='Optional residential address', null=True)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], default='single', max_length=10)),
                ('military_status', models.CharField(choices=[('temporary_exemption', 'Temporary Exemption'), ('permanent_exemption', 'Permanent Exemption'), ('evasion', 'Evasion'), ('postponed', 'Postponed'), ('completed', 'Completed'), ('not_applicable', 'Not Applicable'), ('other', 'Other')], max_length=20)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contractor', 'Contractor'), ('intern', 'Intern')], default='full_time', max_length=20)),
                ('employment_state', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('terminated', 'Terminated'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('hire_date', models.DateField(verbose_name='Hire Date')),
                ('current_salary', models.DecimalField(decimal_places=2, default=0, help_text='Current salary (latest)', max_digits=12)),
                ('is_attendance_exempt', models.BooleanField(default=False, help_text='If true, attendance policies do not apply')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_employees', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_employees', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.jobtitle')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'indexes': [models.Index(fields=['phone_number1'], name='employees_e_phone_n_f6ec03_idx'), models.Index(fields=['fingerprint_id'], name='employees_e_fingerp_f13294_idx'), models.Index(fields=['national_id'], name='employees_e_nationa_045917_idx'), models.Index(fields=['employment_state'], name='employees_e_employm_45e869_idx')],
            },
        ),
    ]
