# Generated by Django 5.2.7 on 2026-03-29 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_department_and_more'),
        ('permissions', '0002_employeerole'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='employees', through='permissions.EmployeeRole', through_fields=('employee', 'role'), to='permissions.role'),
        ),
    ]
