# Generated by Django 5.2.7 on 2026-02-08 16:23

import employees.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_email_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=employees.models.NullableEmailField(blank=True, default=None, max_length=254, null=True, unique=True),
        ),
    ]
